using Acidmanic.Utilities.Results;
using CoreCommandLine;
using CoreCommandLine.Attributes;

namespace Acidmanic.Utilities.SourceResourceTool.Commands.Arguments
{
    [CommandName("class-name","cn")]
    public class ClassName:CommandBase
    {
        public override bool Execute(Context context, string[] args)
        {
            if (AmIPresent(args))
            {
                var value = ReadMyValue(args);

                context.Set(nameof(ClassName),value);
                
                return true;
            }

            return false;
        }

        public override string Description => "The name of the class which its code is going to be AutoGenerated";
        
        public Result<string> ReadMyValue(string[] args)
        {
            var index = IndexOf(NameBundle, args);

            if (index > 0 && index < args.Length - 1)
            {
                return new Result<string>(true, args[index + 1]);
            }

            return new Result<string>().FailAndDefaultValue();
        }
    }
}